var app = angular.module('timelineApp', []);
var marginTop = 0;
var marginLeft = 0;

app.controller('timelineController', function($scope){
  $scope.items=[
    {year: '1979',
     image: "https://www.fxguide.com/wp-content/uploads/2013/07/pose_left.jpg?67371f",
     info: "Ed Catmull is recruited by George Lucas from The New York Institute of Technology to head Lucasfilm's Computer Division, a group charged with developing state-of-the-art computer technology for the film industry. Lucas's wish list: a digital (nonlinear) film editing system, a digital sound editing system, a digital film printer, and further exploration of computer graphics."
    },
    {year: "1983", image: "http://www.deepfocusreview.com/reviews/images/toystory.2.jpg", info: "John Lasseter is invited to join the graphics group at Lucasfilm's Computer Division, and works on Thomas Porter's 1984 pool ball image as well as the short film The Adventures of André & Wally B. He would be hired full-time the following year, joining the Computer Division as an 'Interface Designer.'"},
    {year: "1984", image: "https://40.media.tumblr.com/c258002af84cb9f13c73035d5decabb6/tumblr_mu8jyvJIZT1rcb0d2o1_500.jpg", info: "A partially completed version of The Adventures of André & Wally B. premieres at SIGGRAPH. It is the first short film created by the future animation studio. It features ground-breaking technology such as complex flexible characters, hand-painted textures, and motion blur."},
    {year: "1986", image: "http://pixartimes.com/wp-content/uploads/2014/12/Luxo-Jr-Title-Card.jpg", info: "Steve Jobs purchases the Computer Graphics Division from George Lucas and establishes an independent company to be christened 'Pixar.' At this time about 44 people are employed. Luxo Jr. is completed. The short film, John Lasseter’s directorial debut, is unveiled in August at SIGGRAPH and then screened for general audiences at Los Angeles-area theaters in November. Luxo Jr. will be the first three-dimensional  computer animated film to be nominated for the Best Animated Short Film Oscar®."},
    {year: "1987", image: "http://www.asdreams.org/magazine/videophile/red's%20dream%203.jpg", info: "Red’s Dream is completed. Its rain effect and complexity of lighting pose new technological challenges for the team and allow a study in creating mood and atmosphere. A portion of the film is rendered entirely on the Pixar Image Computer. Also directed by John Lasseter, the short film has its premiere in July at SIGGRAPH."},
    {year: "1988", image: "https://i.ytimg.com/vi/lLnrn9Nw1iM/maxresdefault.jpg", info: "Tin Toy is completed. A partially completed version is screened for SIGGRAPH audiences in August, and the film receives its official premiere later that year at the Ottawa International Film Fest. Tin Toy will be the firstcomputer animated film to receive an Academy Award® when it is named Best Animated Short Film of 1988.Pixar’s new animation system, Menv (short for 'modeling evnironment'), comes online."},
    {year: "1989", image: "http://vignette1.wikia.nocookie.net/pixar/images/6/68/Knick_Knack_Snowglobe.jpg/revision/latest?cb=20100131154220", info: "Knick Knack is completed. A work-in-progress version is screened at that year’s SIGGRAPH. It is the first of the company's animations to be produced in stereoscopic 3D. The first commercial version of RenderMan® is released—and will go on to become the industry standard software for rendering computer graphics in film. Pixar begins making commercials—and would later twice win the CLIO Award.  Pete Docter and Andrew Stanton join the company."},
    {year: "1991", image: "https://grtfilm.files.wordpress.com/2014/02/airport_1.jpg?w=640&h=435", info: "Disney and Pixar announce an agreement 'to make anddistribute at least one computer-generated animated movie.'"},
    {year: "1995", image: "http://cdn.business2community.com/wp-content/uploads/2015/06/toy-story_400x300.jpg", info: "Toy Story, the world’s first computer animated feature film,is released in theaters on November 22. Toy Story also becomes the highest grossing film of 1995, making $192 million domestically and $362 million worldwide. Toy Story will be nominated for Best Original Song, Best Original Score, and Best Original Screenplay by the Academy of Motion Pictures Arts and Sciences. David DiFrancesco receives a Scientific and Engineering Academy Award® for Film Input Scanning.Pixar opens its initial public offering on November 28.  It is the largest IPO of the year."},
    {year: "1996", image: "https://dlrdarlings.files.wordpress.com/2015/03/mv5bmja3mtu1mtu5mf5bml5banbnxkftztcwmjeynzi0na-_v1_sx640_sy720_.jpg", info: "John Lasseter receives a Special Achievement Oscar® from the Academy of Motion Picture Arts and Sciences for his 'inspired leadership of the Pixar Toy Story Team resulting in the first feature-length computer animated film.' Ed Catmull, Alvy Ray Smith, Thomas Porter and Tom Duff receive the Sciences Scientific and Engineering Academy Award® for their pioneering inventions in digital image compositing."},
    {year: "1997", image: "https://i.ytimg.com/vi/xD5Hpk3oEVA/maxresdefault.jpg", info: "The Walt Disney Studios and Pixar Animation Studios announce an agreement to jointly produce five movies over 10 years. Pixar now employs 375 people. Geri’s Game is completed. It premieres at Laemmle's Monica Theater in Santa Monica on November 24. It will be Pixar's second winner of the Best Animated Short Film Academy Award®. William Reeves receives the Scientific and Engineering Academy Award® for Particle Systems; Rick Sayre receives the Technical Achievement Academy Award® for Direct Input Device."},
    {year: "1998", image: "http://aimg.disneystore.com/content/ds/skyway/2012/category/full/cp_FWB_BugsLife_20120926.jpg", info: "A Bug's Life is released in theaters on November 25, accompanied by the short film Geri’s Game. A Bug's Life breaks all previous U.S. Thanksgiving weekend box-office records. It will be nominated for the Best Original Musical or Comedy Score Oscar®. Eben Ostby, William Reeves, and Tom Duff receive the Scientific and Engineering Academy Award® for Marionette 3-D Animation Systems,  and Thomas Porter receives The Scientific Academy Award® for Digital Painting."},
    {year: "1999", image: "http://docfilms.uchicago.edu/dev/images/2014/spring/2014-04-18.jpg", info: "Toy Story 2 is released in theaters on November 24. It is the first film in history to be entirely created, mastered and exhibited digitally, and is the first animated sequel to gross more than its original.   It will be nominated for the Best Original Song Oscar® for 'When She Loved Me,' written by Randy Newman. Toy Story 2 breaks box-office opening weekend records in United States, United Kingdom and Japan. David DiFrancesco receives the Technical Achievement Academy Award® for Laser Film Recording, which is dubbed PIXARVISION."},
    {year: "2000", image: "http://www.lacimorgancreations.com/wp-content/uploads/2012/01/pixar-main-gate.jpg", info: "For the Birds is completed. It premieres at the Annecy International Film Festival in France on June 5. It will eventually win the Academy Award® for Best Animated Short Film . Pixar moves to its new building in Emeryville, CA, on November 27."},
    {year: "2001", image: "http://www.windsorstar.com/cms/binary/3171923.jpg?size=640x420", info: "Monsters, Inc. is released in theaters on November 2, accompanied by For the Birds. Monsters, Inc. reaches over $100 million in domestic box-office in just 9 days—faster than any animated film in history. It will receive two Academy Award® nominations, including Best Song; Randy Newman will take home the Oscar® for 'If I Didn't Have You,' from the Monsters, Inc. soundtrack. Rob Cook, Loren Carpenter and Ed Catmull receive an Academy Award of Merit® for Significant Advances in the Field of Motion Picture Rendering.Pixar now numbers over 600 employees. Co-founder Ed Catmull is named Pixar's President."},
    {year: "2002", image: "https://upload.wikimedia.org/wikipedia/commons/a/ac/A_bug's_land.JPG", info: "Mike's New Car, the first-ever Pixar short featuring characters from another Pixar film, premieres on September 17.  It is featured as part of the Monster, Inc. DVD and VHS release. The short will receive an Academy Award® nomination for Best Animated Short Film. 'a bug's land' attraction opens on October 7 at Disney California Adventure Park."},
    {year: "2003", image: "https://d3gqo5sd50q7na.cloudfront.net/system/shots/761/original/finding-nemo.20130415090444.jpg?1366016684", info: "Finding Nemo is released in theaters on May 30, accompanied by a reamastered version of Knick Knack. Finding Nemo breaks opening weekend box-office records domestically for an animated feature. Finding Nemo goes on to be nominated for four Academy Awards and win the Oscar for Best Animated Feature. Boundin' Premieres and will be nominated for the Academy Award as Best Animated Short Film."},
    {year: "2004", image: "https://secure.parksandresorts.wdpromedia.com/resize/mwImage/1/630/354/90/wdpromedia.disney.go.com/media/wdpro-assets/parks-and-tickets/attractions/epcot/turtle-talk-with-crush/turtle-talk-with-crush-00.jpg?17072014161448", info: "The Incredibles is released in theaters on Novemeber 5. Its first weekend box office of over $70 million breaks all Pixar records. It will be nominated for four Academy Awards®, and win two:  Best Animated Feature Film and Achievement in Sound Editing. Finding Nemo becomes the best-selling DVD of all time, selling more than 24 million copies in North America alone. 'Turtle  Talk with Crush' opens at Walt Disney World Resort's The Seas with Nemo and Friends Pavillion on November 11."},
    {year: "2005", image: "http://jaypgreene.files.wordpress.com/2008/06/moma-pixar-www-rationalistic-com.jpg", info: "For the Birds is completed. It premieres at the Annecy International Film Festival in France on June 5. It will eventually win the Academy Award® for Best Animated Short Film . Pixar moves to its new building in Emeryville, CA, on November 27.The world premiere of One Man Band takes place at the Annecy International Film Festival. One Man Band will be nominated for the Best Animated Short Film Academy Award®. Pixar's first external exhibition of original artwork, Pixar: 20 Years of Animation, opens at New York Museum of Modern Art on December 14."},
    {year: "2006", image: "https://fortunedotcom.files.wordpress.com/2014/12/ap060124011531.jpg?quality=80", info: "Pixar celebrates its 20th anniversary. Cars is released in theaters on June 9, and will receive Academy Award® nominations for Best Animated Feature and Best Original Song. Disney announces its agreement to purchase Pixar. Ed Catmull is named President and John Lasseter is named Chief Creative Officer of Disney and Pixar Animation Studios. ifted premieres at Laemmle's Colorado Theater on September 11 and will be nominated for the Best Animated Short Film Oscar®. Story artist Joe Ranft is named a Disney Legend. David Baraff, Michael Kass and Andy Witkin receive the Scientific and Engineering Academy Award® for Cloth Simulation. Ed Catmull and Tony DeRose receive the Technical Achievement Academy Award® for Subdivision Surfaces."},
    {year: "2007", image: "https://i.ytimg.com/vi/KyhIVD8lBEw/maxresdefault.jpg", info: "Ratatouille is released in theaters on June 29. Ratatouille will be nominated for five Academy Awards® and win the Oscar® for Best Animated Feature. 'Finding Nemo Submarine Voyage' opens at Disneyland Resort's Tomorrowland on June 11."},
    {year: "2008", image: "http://www.hellostonehenge.com/wp-content/uploads/2014/10/wall-e-4.jpg", info: "WALL•E is released in theaters on June 27.  The film will be nominated for six Academy Awards®, and take home the Oscar® for Best Animated Feature Film. Presto premieres at the Annecy International Film Festival and will be nominated for the Best Animated Short Film Academy Award®.The first set of Cars Toons (Rescue Squad Mater, Mater the Greater,and El Materdor) are completed.WALL•E Producer and renowned industry effects veteran Jim Morris is named General Manager of Pixar."},
    {year: "2009", image: "http://www.hdwallpapers.in/walls/pixars_up_dual_monitor_hd-HD.jpg", info: "Up is the first animated feature to open the Cannes Film Festival and debuts in theaters on May 29 with the original short Partly Cloudy. Up will be nominated for five Academy Awards®, including Best Picture; it will take home the Oscars® for Best Animated Feature Film and Best Original Score. The Academy of Motion Pictures and Sciences honors Ed Catmull with the Gordon E. Sawyer Award®."},
    {year: "2010", image: "http://media2.popsugar-assets.com/files/2010/06/24/1/192/1922398/ActorTom_Todd_60743045_Max/i/Pictures-Britney-Spears-Tom-Hanks-Tim-Allen-Michael-Keaton-Toy-Story-3-Premiere-2010-06-14-100859.jpg", info: "Toy Story 3 is released in theaters on June 18. It will become the highest-grossing animated film of all time, and the first to reach the billion dollar mark. Toy Story 3 will be nominated for five Academy Awards®, and win the Oscars® for Best Animated Feature Film and Best Original Song, 'We Belong Together,' written and performed by Randy Newman.  Day and Night debuts at the Annecy International Film Festival. It will be nominated for the Best Animated Short Film Academy Award®. John Lasseter is honored with the Producers Guild of America's 2010. David O. Selznick Achievement Award in Motion Pictures, making him the first producer of animated films to receive this award. Per Christensen receives the Scientific and Engineering Academy Award® for Point-based Rendering for Indirect Ilumination and Ambient Occlusion."},
    {year: "2011", image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRH6q8BXtXYO1cjlE5eQQ0G-YP929qjTBKB7iCGmtOsPdYCR__k", info: "Pixar celebrates its 25th Anniversary and completes construction of a new building on its Emeryville campus. Cars 2 is released in theaters on June 24, accompanied by the firs Toy Story Toon, Hawaiian Vacation. La Luna premieres and will be nominated for the Academy Award® for Best Animated Short Film . David M. Laur receives the Technical Achievement Academy Award® for Alfred Render Queue Management System."},
    {year: "2012", image: "http://vignette2.wikia.nocookie.net/pixar/images/5/59/Brave-2012-1-.jpg/revision/latest?cb=20120727182532", info: "Brave is released in theaters on June 22, accompanied bythe short La Luna. Brave is nominated and wins the Academy Award® for Best Animated Feature Film .Partysaurus Rex, Time Travel Mater, and The Legend of Mor'du are all released."},
    {year: "2013", image: "http://cdn2-www.comingsoon.net/assets/uploads/2013/01/file_98454_0_pixarfuture4.jpg", info: "Monsters University is released in theaters on June 21, accompanied by the short The Blue Umbrella. ABC Televised special Toy Story Of Terror and Tales From Radiator Springs (Hiccups, Spinning, Bugged), are all released."},
    {year: "2015", image: "http://cdn.uinterview.com/wp-content/uploads/2015/06/news-inside-out-premiere.jpg", info: "For the first time Pixar released two animated features in the same year, Inside Out along with The Good Dinosaur. Two animated shorts were also released, Lava and Sanjay's Super Team with the feature films respectively. An exhibit, 'The Science Behind Pixar begins touring in Boston, MA."},
    {year: "2016", image: "https://i.ytimg.com/vi/3JNLwlcPBPI/maxresdefault.jpg", info: "Pixar celebrates its 30th anniversary. Inside Out won Best Animated Feature at the Academy Awards. Finding Dory is set to release on June 17."},
    ];
  $scope.slide = $scope.items[0];
  $scope.selectSlide = function(item){
    $scope.slide = item;
  };
  $scope.tlStyle = {
    'float': 'left',
    'margin-left': '0px',
    'display': 'block',
    'margin-top' : '0px',
   };
  $scope.clickEnable = true;
  $scope.moveRight = function(){
    if (marginLeft !== -2500){
      marginLeft = +$scope.tlStyle['margin-left'].replace('px', '') + -100;
    };
    $scope['margin-left'] = marginLeft + 'px';
    return $scope['margin-left'];
  };
  $scope.moveLeft = function(){
    if (marginLeft !== 0){
      marginLeft = +$scope.tlStyle['margin-left'].replace('px', '') + 100;
    };
    $scope['margin-left'] = marginLeft + 'px';
    return $scope['margin-left'];
  };
  $scope.moveDown = function(){
    if (marginTop !== -2500){
        marginTop = +$scope.tlStyle['margin-top'].replace('px', '') + -100;
    };
     $scope['margin-top'] = marginTop + 'px';
     return $scope['margin-top'];
  };
  $scope.moveUp = function(){
    if (marginTop !== 0 ){
        marginTop = +$scope.tlStyle['margin-top'].replace('px', '') + 100;
   };
    $scope['margin-top'] = marginTop + 'px';
    return $scope['margin-top'];
  };
});
